name = "LinearInterpolations"
uuid = "b20c7882-2490-4592-a606-fbbfe9e745e8"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.4"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Adapt = "3.3.1"
ArgCheck = "1, 2.0"
StaticArrays = "1"
julia = "1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools", "CUDA", "StructArrays", "StaticArrays"]
